# Generated by Django 4.2.5 on 2023-09-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_student_oquv_tanigan_student_darajasi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_arab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField(max_length=100)),
                ('dars_soati', models.PositiveIntegerField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('telefon2', models.CharField(max_length=100)),
                ('darajasi', models.CharField(max_length=100)),
                ('Oquv_tanigan', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_matem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField(max_length=100)),
                ('dars_soati', models.PositiveIntegerField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('telefon2', models.CharField(max_length=100)),
                ('darajasi', models.CharField(max_length=100)),
                ('Oquv_tanigan', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_mental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField(max_length=100)),
                ('dars_soati', models.PositiveIntegerField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('telefon2', models.CharField(max_length=100)),
                ('darajasi', models.CharField(max_length=100)),
                ('Oquv_tanigan', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_rus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField(max_length=100)),
                ('dars_soati', models.PositiveIntegerField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('telefon2', models.CharField(max_length=100)),
                ('darajasi', models.CharField(max_length=100)),
                ('Oquv_tanigan', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
