# Generated by Django 4.2.5 on 2023-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_teachertype_student_qaysi_ustoz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachertype',
            name='nomi',
            field=models.CharField(max_length=50),
        ),
    ]
