# Generated by Django 4.2.5 on 2023-09-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_remove_student_qaysi_ustoz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_matem',
            name='qaysi_ustoz',
        ),
        migrations.RemoveField(
            model_name='student_mental',
            name='qaysi_ustoz',
        ),
        migrations.RemoveField(
            model_name='student_rus',
            name='qaysi_ustoz',
        ),
        migrations.AddField(
            model_name='student',
            name='qaysi_ustoz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myfiles.teachertype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='dars_soati',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='yosh',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Student_arab',
        ),
        migrations.DeleteModel(
            name='Student_matem',
        ),
        migrations.DeleteModel(
            name='Student_mental',
        ),
        migrations.DeleteModel(
            name='Student_rus',
        ),
    ]
