# Generated by Django 4.2.5 on 2023-09-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_remove_student_matem_qaysi_ustoz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dars_soati',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='yosh',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachertype',
            name='nomi',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Student_rus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField(max_length=100)),
                ('dars_soati', models.PositiveIntegerField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('telefon2', models.CharField(max_length=100)),
                ('darajasi', models.CharField(max_length=100)),
                ('Oquv_tanigan', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('qaysi_ustoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.teachertype')),
            ],
        ),
        migrations.CreateModel(
            name='Student_mental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField(max_length=100)),
                ('dars_soati', models.PositiveIntegerField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('telefon2', models.CharField(max_length=100)),
                ('darajasi', models.CharField(max_length=100)),
                ('Oquv_tanigan', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('qaysi_ustoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.teachertype')),
            ],
        ),
        migrations.CreateModel(
            name='Student_matem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField(max_length=100)),
                ('dars_soati', models.PositiveIntegerField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('telefon2', models.CharField(max_length=100)),
                ('darajasi', models.CharField(max_length=100)),
                ('Oquv_tanigan', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('qaysi_ustoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.teachertype')),
            ],
        ),
        migrations.CreateModel(
            name='Student_arab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField(max_length=100)),
                ('dars_soati', models.PositiveIntegerField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('telefon2', models.CharField(max_length=100)),
                ('darajasi', models.CharField(max_length=100)),
                ('Oquv_tanigan', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('qaysi_ustoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.teachertype')),
            ],
        ),
    ]
