# Generated by Django 4.2.5 on 2023-09-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_alter_student_dars_soati_alter_student_yosh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarajaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='darajasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.darajatype'),
        ),
        migrations.AlterField(
            model_name='student_arab',
            name='darajasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.darajatype'),
        ),
        migrations.AlterField(
            model_name='student_matem',
            name='darajasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.darajatype'),
        ),
        migrations.AlterField(
            model_name='student_mental',
            name='darajasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.darajatype'),
        ),
        migrations.AlterField(
            model_name='student_rus',
            name='darajasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.darajatype'),
        ),
    ]
