# Generated by Django 4.2.5 on 2023-09-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0009_darajatype_alter_student_darajasi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QayerdanTaniganType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Oquv_tanigan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.qayerdantanigantype'),
        ),
        migrations.AlterField(
            model_name='student_arab',
            name='Oquv_tanigan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.qayerdantanigantype'),
        ),
        migrations.AlterField(
            model_name='student_matem',
            name='Oquv_tanigan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.qayerdantanigantype'),
        ),
        migrations.AlterField(
            model_name='student_mental',
            name='Oquv_tanigan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.qayerdantanigantype'),
        ),
        migrations.AlterField(
            model_name='student_rus',
            name='Oquv_tanigan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.qayerdantanigantype'),
        ),
    ]
