# Generated by Django 4.2.5 on 2023-09-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0011_tolov'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolov',
            name='qaycha_tolov',
            field=models.PositiveIntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tolov',
            name='qolgan_tolov',
            field=models.PositiveIntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
