# Generated by Django 4.2.5 on 2023-09-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0012_tolov_qaycha_tolov_tolov_qolgan_tolov'),
    ]

    operations = [
        migrations.CreateModel(
            name='TolovType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oy1', models.CharField(max_length=50)),
                ('oy2', models.CharField(max_length=50)),
                ('oy3', models.CharField(max_length=50)),
                ('oy4', models.CharField(max_length=50)),
                ('oy5', models.CharField(max_length=50)),
                ('oy6', models.CharField(max_length=50)),
                ('oy7', models.CharField(max_length=50)),
                ('oy8', models.CharField(max_length=50)),
                ('oy9', models.CharField(max_length=50)),
                ('oy10', models.CharField(max_length=50)),
                ('oy11', models.CharField(max_length=50)),
                ('oy12', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tolov',
            name='Qaysi_oy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myfiles.tolovtype'),
            preserve_default=False,
        ),
    ]
