# Generated by Django 4.2.5 on 2023-09-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0015_rename_gurux_nomi_juft_kunlari_ism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tolov',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_arab',
            name='tolov',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_matem',
            name='tolov',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_mental',
            name='tolov',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_rus',
            name='tolov',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
