# Generated by Django 4.2.5 on 2023-09-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0019_tolovqilganyokiqilmagantype_alter_tolov_tolov_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolovqilganyokiqilmagantype',
            name='nomi',
            field=models.CharField(max_length=50),
        ),
    ]
