# Generated by Django 4.2.2 on 2023-10-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0024_tolovqilganyokiqilmagantype_25_30_tolov25_30'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keldi', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
