# Generated by Django 4.2.2 on 2023-10-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0025_bor'),
    ]

    operations = [
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
