# Generated by Django 4.2.2 on 2023-10-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0026_juft_kunlari_oquvchi1'),
    ]

    operations = [
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
