# Generated by Django 4.2.2 on 2023-10-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0027_juft_kunlari_oquvchi2'),
    ]

    operations = [
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi10',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi11',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi12',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi13',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi14',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi15',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi4',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi5',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi6',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi7',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi8',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juft_kunlari',
            name='oquvchi9',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
