# Generated by Django 4.2.2 on 2023-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0028_juft_kunlari_oquvchi10_juft_kunlari_oquvchi11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi12',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi13',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi14',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi15',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='juft_kunlari',
            name='oquvchi9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
