# Generated by Django 4.2.2 on 2023-10-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0029_alter_juft_kunlari_oquvchi10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bor',
            name='keldi',
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi10_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi11_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi12_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi13_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi14_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi15_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi1_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi2_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi3_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi4_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi5_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi6_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi7_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi8_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bor',
            name='oquvchi9_davomat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
