# Generated by Django 4.2.2 on 2023-10-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0030_remove_bor_keldi_bor_oquvchi10_davomat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bor',
            name='ism',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
