# Generated by Django 4.2.2 on 2023-11-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0031_bor_ism'),
    ]

    operations = [
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi1',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi12',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi13',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi14',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi15',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toq_kunlari',
            name='oquvchi9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
