# Generated by Django 4.2.2 on 2023-11-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0032_toq_kunlari_oquvchi1_toq_kunlari_oquvchi10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorToq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('oquvchi1_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi2_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi3_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi4_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi5_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi6_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi7_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi8_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi9_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi10_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi11_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi12_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi13_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi14_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('oquvchi15_davomat', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
