# Generated by Django 4.2.2 on 2023-11-06 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0033_bortoq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_ketgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('telefon2', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('qaysi_ustoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.teachertype')),
            ],
        ),
    ]
