# Generated by Django 4.2.2 on 2023-11-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0034_student_ketgan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('yosh', models.PositiveIntegerField(max_length=100)),
                ('dars_soati', models.PositiveIntegerField(max_length=100)),
                ('manzil', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('telefon2', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('Oquv_tanigan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.qayerdantanigantype')),
                ('darajasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.darajatype')),
                ('qaysi_ustoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.teachertype')),
            ],
        ),
    ]
