# Generated by Django 4.2.2 on 2023-11-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0036_qarzdorlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov5_10',
            name='tolov_filter',
            field=models.CharField(max_length=50),
        ),
    ]
