# Generated by Django 4.2.2 on 2023-11-09 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0037_alter_tolov5_10_tolov_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov10_15',
            name='tolov_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.tolovqilganyokiqilmagantype_5_10'),
        ),
    ]
