# Generated by Django 4.2.2 on 2023-11-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0038_alter_tolov10_15_tolov_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov10_15',
            name='tolov_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.tolovqilganyokiqilmagantype_10_15'),
        ),
    ]
