# Generated by Django 4.2.2 on 2023-11-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0039_alter_tolov10_15_tolov_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tolovtype',
            name='oy10',
        ),
        migrations.RemoveField(
            model_name='tolovtype',
            name='oy11',
        ),
        migrations.RemoveField(
            model_name='tolovtype',
            name='oy12',
        ),
        migrations.RemoveField(
            model_name='tolovtype',
            name='oy2',
        ),
        migrations.RemoveField(
            model_name='tolovtype',
            name='oy3',
        ),
        migrations.RemoveField(
            model_name='tolovtype',
            name='oy4',
        ),
        migrations.RemoveField(
            model_name='tolovtype',
            name='oy5',
        ),
        migrations.RemoveField(
            model_name='tolovtype',
            name='oy6',
        ),
        migrations.RemoveField(
            model_name='tolovtype',
            name='oy7',
        ),
        migrations.RemoveField(
            model_name='tolovtype',
            name='oy8',
        ),
        migrations.RemoveField(
            model_name='tolovtype',
            name='oy9',
        ),
    ]
