# Generated by Django 4.2.2 on 2023-11-10 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0040_remove_tolovtype_oy10_remove_tolovtype_oy11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov5_10',
            name='tolov_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.tolovqilganyokiqilmagantype_5_10'),
        ),
    ]
