# Generated by Django 4.2.2 on 2023-11-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0042_all_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
    ]
