# Generated by Django 4.2.2 on 2023-11-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0043_fanlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='XarajatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Xarajatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('qancha_pul_ketgan', models.PositiveIntegerField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('XarajatTuri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.qayerdantanigantype')),
            ],
        ),
    ]
