# Generated by Django 4.2.2 on 2023-11-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0044_xarajattype_xarajatlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xarajatlar',
            name='XarajatTuri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.xarajattype'),
        ),
    ]
